# Generated by Django 5.1 on 2024-08-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
