# Generated by Django 5.1 on 2024-08-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
