# Generated by Django 5.1 on 2024-08-26 05:17

from django.db import migrations, models

def create_tags(apps, schema_editor):
    Tag = apps.get_model('inquiries', 'Tag')
    tags = [
        '認知症', 'せん妄', '身体障碍', '精神障碍', '昼夜逆転', '寝たきり',
        '施設', '家族間トラブル', '介護認定', '介護制度', '障碍者手帳','ヤングケアラー', '老々介護',
        '依存症','ギャンブル','薬物','アルコール','精神病','終末期ケア','居宅介護',
    ]
    for tag_name in tags:
        Tag.objects.create(name=tag_name)

class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_inquiry_views'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='inquiry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='inquiries.tag'),
        ),
        migrations.RunPython(create_tags),
    ]
