# Generated by Django 5.1 on 2024-08-29 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def create_tags(apps, schema_editor):
    Tag = apps.get_model('inquiries', 'Tag')
    tags = [
        '認知症', 'せん妄', '身体障碍', '精神障碍', '昼夜逆転', '寝たきり',
        '施設', '家族間トラブル', '介護認定', '介護制度', '障碍者手帳','ヤングケアラー', '老々介護',
        '依存症','ギャンブル','薬物','アルコール','精神病','終末期ケア','居宅介護',
    ]
    for tag_name in tags:
        Tag.objects.create(name=tag_name)

class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_alter_inquiry_title_savedresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiries.inquiry')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('responder', 'inquiry')},
            },
        ),
        migrations.RunPython(create_tags),
    ]
