# Generated by Django 5.1 on 2024-08-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jigyousha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todofuken_code', models.CharField(max_length=10)),
                ('no', models.CharField(max_length=20)),
                ('todofuken_name', models.CharField(max_length=100)),
                ('shichoson_name', models.CharField(max_length=100)),
                ('jigyousho_name', models.CharField(max_length=255)),
                ('jigyousho_name_kana', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('houjin_name', models.CharField(max_length=255)),
                ('jigyousho_number', models.CharField(max_length=20)),
                ('available_days', models.CharField(blank=True, max_length=255, null=True)),
                ('special_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jigyousha',
            },
        ),
    ]
