# Generated by Django 5.1 on 2024-08-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigyousha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigyousha',
            name='fax_number',
            field=models.TextField(blank=True, db_column='FAX番号', null=True),
        ),
        migrations.AddField(
            model_name='jigyousha',
            name='houjin_number',
            field=models.FloatField(blank=True, db_column='法人番号', null=True),
        ),
        migrations.AddField(
            model_name='jigyousha',
            name='kaigo_hoken',
            field=models.TextField(blank=True, db_column='介護保険の通常の指定基準を満たしている', null=True),
        ),
        migrations.AddField(
            model_name='jigyousha',
            name='kogei_shogaisha_taiyo',
            field=models.TextField(blank=True, db_column='高齢者の方と障害者の方が同時一体的に利用で', null=True),
        ),
        migrations.AddField(
            model_name='jigyousha',
            name='notes',
            field=models.TextField(blank=True, db_column='備考', null=True),
        ),
        migrations.AddField(
            model_name='jigyousha',
            name='phone_number',
            field=models.TextField(blank=True, db_column='電話番号', null=True),
        ),
        migrations.AddField(
            model_name='jigyousha',
            name='shogai_fukushi',
            field=models.TextField(blank=True, db_column='障害福祉の通常の指定基準を満たしている', null=True),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='address',
            field=models.TextField(db_column='住所'),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='available_days',
            field=models.TextField(blank=True, db_column='利用可能曜日', null=True),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='building_name',
            field=models.TextField(blank=True, db_column='方書（ビル名等）', null=True),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='capacity',
            field=models.FloatField(blank=True, db_column='定員', null=True),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='houjin_name',
            field=models.TextField(blank=True, db_column='法人の名称', null=True),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='jigyousho_name',
            field=models.TextField(db_column='事業所名'),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='jigyousho_name_kana',
            field=models.TextField(db_column='事業所名カナ'),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='jigyousho_number',
            field=models.TextField(blank=True, db_column='事業所番号', null=True),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='latitude',
            field=models.FloatField(blank=True, db_column='緯度', null=True),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='longitude',
            field=models.FloatField(blank=True, db_column='経度', null=True),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='no',
            field=models.TextField(db_column='No'),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='service_type',
            field=models.TextField(db_column='サービスの種類'),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='shichoson_name',
            field=models.TextField(db_column='市区町村名'),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='special_notes',
            field=models.TextField(blank=True, db_column='利用可能曜日特記事項', null=True),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='todofuken_code',
            field=models.BigIntegerField(db_column='都道府県コード又は市町村コード'),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='todofuken_name',
            field=models.TextField(db_column='都道府県名'),
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='url',
            field=models.TextField(blank=True, db_column='URL', null=True),
        ),
    ]
