# Generated by Django 5.1 on 2024-08-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigyousha', '0002_jigyousha_fax_number_jigyousha_houjin_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jigyousha',
            name='id',
        ),
        migrations.AlterField(
            model_name='jigyousha',
            name='no',
            field=models.TextField(db_column='No', primary_key=True, serialize=False),
        ),
    ]
