# Generated by Django 5.1 on 2024-08-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigyousha', '0003_remove_jigyousha_id_alter_jigyousha_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='SJigyousha',
            fields=[
                ('todofuken_code', models.BigIntegerField(db_column='都道府県コード又は市区町村コード')),
                ('no', models.IntegerField(db_column='NO（※システム内の固有の番号、連番）', primary_key=True, serialize=False)),
                ('shitei_kikan_name', models.TextField(db_column='指定機関名')),
                ('houjin_name', models.TextField(db_column='法人の名称')),
                ('houjin_name_kana', models.TextField(db_column='法人の名称_かな')),
                ('houjin_number', models.BigIntegerField(db_column='法人番号')),
                ('houjin_address_city', models.TextField(db_column='法人住所（市区町村）')),
                ('houjin_address_street', models.TextField(db_column='法人住所（番地以降）')),
                ('houjin_phone_number', models.CharField(db_column='法人電話番号', max_length=20)),
                ('houjin_fax_number', models.CharField(blank=True, db_column='法人FAX番号', max_length=20, null=True)),
                ('houjin_url', models.URLField(blank=True, db_column='法人URL', null=True)),
                ('service_type', models.TextField(db_column='サービス種別')),
                ('jigyousho_name', models.TextField(db_column='事業所の名称')),
                ('jigyousho_name_kana', models.TextField(db_column='事業所の名称_かな')),
                ('jigyousho_number', models.CharField(db_column='事業所番号', max_length=255)),
                ('jigyousho_address_city', models.TextField(db_column='事業所住所（市区町村）')),
                ('jigyousho_address_street', models.TextField(db_column='事業所住所（番地以降）')),
                ('jigyousho_phone_number', models.CharField(db_column='事業所電話番号', max_length=20)),
                ('jigyousho_fax_number', models.CharField(blank=True, db_column='事業所FAX番号', max_length=20, null=True)),
                ('jigyousho_url', models.URLField(blank=True, db_column='事業所URL', null=True)),
                ('jigyousho_latitude', models.FloatField(blank=True, db_column='事業所緯度', null=True)),
                ('jigyousho_longitude', models.FloatField(blank=True, db_column='事業所経度', null=True)),
                ('available_time_weekdays', models.TextField(blank=True, db_column='利用可能な時間帯（平日）', null=True)),
                ('available_time_saturday', models.TextField(blank=True, db_column='利用可能な時間帯（土曜）', null=True)),
                ('available_time_sunday', models.TextField(blank=True, db_column='利用可能な時間帯（日曜）', null=True)),
                ('available_time_holiday', models.TextField(blank=True, db_column='利用可能な時間帯（祝日）', null=True)),
                ('closed_days', models.TextField(blank=True, db_column='定休日', null=True)),
                ('available_days_note', models.TextField(blank=True, db_column='利用可能曜日特記事項（留意事項）', null=True)),
                ('capacity', models.IntegerField(blank=True, db_column='定員', null=True)),
            ],
            options={
                'db_table': 'sjigyousha',
            },
        ),
    ]
