# Generated by Django 5.1 on 2025-03-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_create_table'),
        ('chat', '0004_change_table'),
    ]

    operations = [
    ]
