# Generated by Django 5.1 on 2024-09-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to='default_images/'),
        ),
    ]
