# Generated by Django 5.1 on 2024-09-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_default_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inquiry_default_image',
            field=models.ImageField(blank=True, default='default_image/icon_sheep.png', null=True, upload_to='default_images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='responser_default_image',
            field=models.ImageField(blank=True, default='default_image/icon_cap.png', null=True, upload_to='default_images/'),
        ),
    ]
