# Generated by Django 5.1 on 2025-01-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_default_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='inquiry_default_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='responser_default_image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='default_images/icon_cap.jpg', upload_to=''),
        ),
    ]
