# Generated by Django 5.1 on 2025-02-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildSupportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, null=True, verbose_name='概要')),
                ('content', models.TextField(verbose_name='内容')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='公開日')),
            ],
            options={
                'verbose_name': '子育て支援情報',
                'verbose_name_plural': '子育て支援情報',
                'ordering': ['-published_date'],
            },
        ),
    ]
